name: Make

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install Dep
      run: |
        sudo apt update
        sudo apt install build-essential libboost-all-dev autoconf automake libtool cmake
        sudo apt install libeigen3-dev
    - name: Install Lib
      run: |
        git clone git@github.com:Cyrus2D/cyruslib.git
