name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Get Results
      run: |
        cd /data1/nader/workspace/robo/AutoTest2D
        ./result.sh gittest
        echo a
        ./result.sh gittest | tail -n 9 >> ${{env.teamdir}}/results.txt
        echo b
        echo "time=$(date)" >> ${GITHUB_ENV}
        echo ${{ env.time }}
        echo b
        echo "commit=$(git rev-parse --short HEAD)" >> ${GITHUB_ENV}
        echo ${{ env.commit }}
    #- name: Create a GitHub release
     # uses: ncipollo/release-action@v1
      #with:
       # tag: ${{ env.commit }}
        #name: Release ${{ env.commit }}
        #body: ${{ env.result }}
    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        file: results.txt
        asset_name: results.txt
        tag: Test ${{ env.commit }}
        overwrite: false
        body: $( cat results.txt )
