name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: |
        mkdir build && cd build && mkdir src
        echo "teamdir=$(pwd)" >> ${GITHUB_ENV}
    - name: Install Lib 
      run: |
        git clone https://${{ secrets.token }}@github.com/Cyrus2D/cyruslib.git
        cd cyruslib
        mkdir build && cd build
        cmake -DTEAM_DIR=${{ env.teamdir }}/build/src/cyruslib ..
        make -j20
        make install
    - name: Build Team
      run: |
        cd build
        cmake -DTEAM_DIR_LIB=${{env.teamdir}}/build/src/cyruslib ..
        make -j20
